"""Local copy of the rs-nexus-os gateway message protocol."""

CMD_IS_SERVER_READY = "is_server_ready"
CMD_GET_DEVICE_INFO = "get_device_info"
CMD_INIT_SYSTEM = "init_system"
CMD_DISCOVER_SENSORS_FOR_SUBJECTS = "discover_sensors_for_subjects"
CMD_CONNECT_SUBJECTS = "connect_subjects"
CMD_DISCONNECT_SUBJECTS = "disconnect_subjects"
CMD_IDENTIFY_SENSOR = "identify_sensor"
CMD_START_STREAM_FOR_SUBJECTS = "start_stream_for_subjects"
CMD_STOP_STREAM_FOR_SUBJECTS = "stop_stream_for_subjects"

EVT_SERVER_READY = "server_ready"
EVT_DEVICE_INFO = "device_info"
EVT_SYSTEM_INITIALIZED = "system_initialized"
EVT_SENSORS_DISCOVERED = "sensors_discovered"
EVT_SENSOR_CONNECTED = "sensor_connected"
EVT_SENSOR_DISCONNECTED = "sensor_disconnected"
EVT_SENSOR_IDENTIFIED = "sensor_identified"
EVT_STREAM_STARTED = "stream_started"
EVT_STREAM_STOPPED = "stream_stopped"
EVT_STREAM_DRAINED = "stream_drained"
EVT_STREAM_WARMUP_STARTED = "stream_warmup_started"
EVT_STREAM_OFFICIAL_STARTED = "stream_official_started"
EVT_STREAM_STARTUP_RETRY = "stream_startup_retry"
EVT_STREAM_STARTUP_FAILED = "stream_startup_failed"
EVT_COMPUTE_RESULT = "compute_result"
EVT_ERROR = "error"
